/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 음성 대화 (STT → LLM → TTS 통합 파이프라인)
         * @description 아이의 음성을 올리면 서버가 STT → LLM → TTS를 한 번에 처리하고
         *     텍스트와 음성(base64 mp3)을 함께 돌려준다. 왕복 1회로 지연 최소화.
         *
         *     **설계 계약**
         *     - STT가 못 알아들어도 `200`이다. `userText: null` + 되묻기 `aiText`가 온다.
         *     - 응답을 받은 앱은 `history`에 user/assistant 두 턴을 추가한다 (`userText`가 null이면 user 턴 생략).
         *     - 오디오 원본은 저장하지 않는다. 응답 헤더 `X-Audio-Retention: none`.
         *     - `aiText`는 한국어교육과정 1~2급 어휘로 생성된다 (FastAPI 프롬프트 담당).
         *     - 타임아웃: Gateway → FastAPI 30초 (3단 파이프라인이라 다른 엔드포인트보다 길다).
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/stt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 음성 → 텍스트
         * @description 음성만 텍스트로 바꾼다. SPEAK/SHADOW 스텝처럼 LLM 응답이 필요 없는 화면에서 쓴다.
         *     인식 결과와 목표 문장의 매칭 판정은 앱 로컬에서 한다.
         *
         *     **인식 실패는 에러가 아니다** — `text: null`로 `200`이 내려간다.
         *     `422 STT_FAILED`는 STT 엔진 자체가 죽었을 때만 쓴다.
         */
        post: operations["stt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/tts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 텍스트 → 음성
         * @description 텍스트를 음성(base64 mp3)으로 바꾼다. DIALOGUE 🔊 버튼, LISTEN 스텝에서 쓴다.
         *
         *     - `voice`는 OpenAI 보이스 ID가 아니라 역할 enum이다. 실제 보이스 매핑은 FastAPI 설정에 둔다.
         *     - 같은 문장의 TTS 결과는 앱이 로컬 캐시한다 — 매번 서버에 묻지 않는다.
         */
        post: operations["tts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 발화 피드백 생성
         * @description 아이의 발화(STT 결과 텍스트)와 목표 문장을 주면 FEEDBACK 스텝에 그릴 피드백 객체를 생성한다.
         *     음성이 아니라 텍스트를 받는다 — STT는 `/ai/stt`에서 이미 끝났다.
         *
         *     **설계 계약**
         *     - `recognizedText: null`도 유효한 요청이다 → 격려 피드백 생성 (`understood/matched: false`).
         *     - `title`에 "틀렸어요"류 문구 금지.
         *     - `matched` 판정 활용(별점 등)은 앱 로컬 책임. 서버는 판정 재료만 준다.
         *     - 발화 기록은 서버에 남지 않는다.
         */
        post: operations["feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description LLM 프롬프트 컨텍스트용 힌트. 앱 로컬의 시나리오 코드와 동일
         * @example LUNCH
         * @enum {string}
         */
        Scenario: "ARRIVAL" | "CLASS" | "LUNCH" | "DISMISSAL";
        /**
         * @description 피드백·번역 생성 언어. KOREAN이면 번역 생략
         * @default KOREAN
         * @example VIETNAMESE
         * @enum {string}
         */
        NativeLanguage: "KOREAN" | "CHINESE" | "VIETNAMESE";
        /** @description 서버 → 앱 오디오. chat과 tts가 동일 구조를 쓴다 — 앱의 재생 코드는 하나면 된다 */
        AudioPayload: {
            /**
             * Format: byte
             * @description base64 인코딩된 mp3 바이너리
             */
            data: string;
            /** @enum {string} */
            format: "mp3";
        };
        ChatResult: {
            /** @description STT 결과. 못 알아들으면 null (에러 아님) */
            userText?: string | null;
            /** @description LLM이 생성한 응답 문장 (한국어교육과정 1~2급 어휘) */
            aiText: string;
            audio: components["schemas"]["AudioPayload"];
        };
        SttResult: {
            /** @description 인식 결과. 못 알아들으면 null (에러 아님) */
            text: string | null;
            /** @description 엔진이 안 주면 null. 화면 표시 금지 */
            confidence: number | null;
        };
        FeedbackResult: {
            /** @description 의미가 통했는가 (아이콘 결정) */
            understood: boolean;
            /** @description 목표 문장과 통했는가 (별점 판정용) */
            matched: boolean;
            /** @description 화면 표시 금지. 내부 판정용 */
            similarity: number;
            /** @description 배너 제목. "틀렸어요"류 문구 금지 */
            title: string;
            /** @description 배너 본문 */
            body?: string | null;
            /** @description 더 자연스러운 표현 */
            naturalSentence?: string | null;
            /** @description 설명문. 불필요하면 null */
            naturalHint?: string | null;
            /** @description 밑줄 칠 어절. 없으면 [] */
            highlightWords: string[];
            /** @description naturalSentence의 모국어 번역. KOREAN이면 null */
            translation?: string | null;
        };
        SuccessEnvelope: {
            /** @enum {boolean} */
            success: true;
            data: Record<string, never>;
        };
        ErrorEnvelope: {
            /** @enum {boolean} */
            success: false;
            error: {
                /** @enum {string} */
                code: "INVALID_PARAMETER" | "UNSUPPORTED_AUDIO_FORMAT" | "AUDIO_TOO_LARGE" | "PAYLOAD_TOO_LARGE" | "STT_FAILED" | "RATE_LIMITED" | "AI_SERVER_ERROR" | "AI_TIMEOUT" | "INTERNAL_ERROR";
                /** @description 개발자용. 아이 화면에 띄우지 않는다 */
                message: string;
                /** @description 문제가 된 파라미터명. 검증 에러에만 채워진다 */
                field?: string | null;
            };
        };
    };
    responses: {
        /** @description 검증 실패 (Gateway) — INVALID_PARAMETER / UNSUPPORTED_AUDIO_FORMAT / AUDIO_TOO_LARGE */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "INVALID_PARAMETER",
                 *         "message": "audio 필드가 없습니다.",
                 *         "field": "audio"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 요청 전체 용량 초과 (Gateway) — PAYLOAD_TOO_LARGE */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "PAYLOAD_TOO_LARGE",
                 *         "message": "요청이 너무 큽니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description STT 엔진 자체 실패 (FastAPI) — 인식 실패(null 반환)와 다르다 */
        SttFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "STT_FAILED",
                 *         "message": "STT 엔진 오류.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description OpenAI API 쿼터 초과 (FastAPI) — RATE_LIMITED */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "RATE_LIMITED",
                 *         "message": "요청이 너무 많습니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description FastAPI 5xx 또는 연결 불가 (Gateway 변환) — AI_SERVER_ERROR */
        AiServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "AI_SERVER_ERROR",
                 *         "message": "추론 서버가 응답하지 않습니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description 타임아웃 초과 (Gateway) — chat 30s, 나머지 15s */
        AiTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "AI_TIMEOUT",
                 *         "message": "추론 시간이 초과되었습니다.",
                 *         "field": null
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 아이의 발화. m4a/wav/webm, 최대 10MB · 60초
                     */
                    audio: string;
                    scenario: components["schemas"]["Scenario"];
                    /**
                     * @description 지금까지의 대화를 담은 JSON 문자열. 없으면 `"[]"`.
                     *     최근 10턴까지만 보낸다 (앱이 자른다).
                     *     형식: `[{"role":"user"|"assistant","content":"..."}]`
                     * @example [{"role":"assistant","content":"불고기 많이 줄까?"}]
                     */
                    history: string;
                    nativeLanguage?: components["schemas"]["NativeLanguage"];
                    /** @description 아이 호칭. 최대 20자 */
                    nickname?: string;
                };
            };
        };
        responses: {
            /** @description 대화 성공 (STT 인식 실패 포함 — userText가 null일 뿐 에러가 아니다) */
            200: {
                headers: {
                    /** @description 오디오 원본 미저장 보증 */
                    "X-Audio-Retention"?: "none";
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "userText": "네, 많이 주세요.",
                     *         "aiText": "그래, 많이 줄게! 맛있게 먹어.",
                     *         "audio": {
                     *           "data": "SUQzBAAA...",
                     *           "format": "mp3"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["ChatResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["SttFailed"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    stt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description m4a/wav/webm, 최대 10MB · 60초
                     */
                    audio: string;
                    /**
                     * @description BCP-47 언어 코드
                     * @default ko-KR
                     */
                    language?: string;
                };
            };
        };
        responses: {
            /** @description 변환 성공 (인식 실패 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "text": "많이 주세요",
                     *         "confidence": 0.94
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["SttResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["SttFailed"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    tts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 읽을 문장
                     * @example 불고기 많이 줄까?
                     */
                    text: string;
                    /**
                     * @description 역할 enum. 실제 보이스 매핑은 FastAPI 담당
                     * @default TEACHER
                     * @enum {string}
                     */
                    voice?: "TEACHER" | "FRIEND";
                    /**
                     * @description 재생 속도. 아동용 기본 느리게
                     * @default 0.9
                     */
                    speed?: number;
                };
            };
        };
        responses: {
            /** @description 합성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "audio": {
                     *           "data": "SUQzBAAA...",
                     *           "format": "mp3"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: {
                            audio: components["schemas"]["AudioPayload"];
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
    feedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description 목표 문장 (앱 번들의 스텝 데이터)
                     * @example 많이 주세요.
                     */
                    targetSentence: string;
                    /**
                     * @description STT 결과. 인식 실패면 null
                     * @example 많이 주세여
                     */
                    recognizedText: string | null;
                    scenario?: components["schemas"]["Scenario"];
                    nativeLanguage?: components["schemas"]["NativeLanguage"];
                    /** @description 아이 호칭. 최대 20자 */
                    nickname?: string;
                };
            };
        };
        responses: {
            /** @description 피드백 생성 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "understood": true,
                     *         "matched": true,
                     *         "similarity": 0.92,
                     *         "title": "잘했어요!",
                     *         "body": "무슨 뜻인지 잘 이해했어요.",
                     *         "naturalSentence": "많이 주세요.",
                     *         "naturalHint": "'주세여'보다 '주세요'가 좋아요.",
                     *         "highlightWords": [
                     *           "주세요"
                     *         ],
                     *         "translation": "Cho mình nhiều nhé."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SuccessEnvelope"] & {
                        data?: components["schemas"]["FeedbackResult"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["AiServerError"];
            504: components["responses"]["AiTimeout"];
        };
    };
}
